CREATE TABLE Person
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    year int
);


CREATE TABLE Book
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int         REFERENCES person (id) ON DELETE SET NULL,
    name      varchar(50) NOT NULL,
    author    varchar(50) NOT NULL,
    year      int
);

alter table book
    add column taken timestamp;

delete from book where true;

INSERT INTO person(name, year)
VALUES ('Ivanon Ivan Ivanovich', 1970);
INSERT INTO person(name, year)
VALUES ('Petrov Petro Petrovich', 1980);
INSERT INTO person(name, year)
VALUES ('Oleksiev Oleksii Oleksiovich', 1990);


INSERT INTO book(person_id, name, author, year, taken)
VALUES (1, 'The Catcher in the Rye', 'J. D. Salinger', 1951,
        to_timestamp('2022-05-21 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'));
INSERT INTO book(person_id, name, author, year, taken)
VALUES (1, 'Being and Time', 'Martin Heidegger', 1927,
        to_timestamp('2022-05-30 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'));
INSERT INTO book(person_id, name, author, year, taken)
VALUES (null, 'Thinking in Java', 'Bruce Eckel', 1998,
        null);
INSERT INTO book(person_id, name, author, year, taken)
VALUES (2, 'Thief of Time', 'Terry Pratchett', 2001,
        to_timestamp('2022-05-30 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'));

select *
from book;

select *
from person;

drop table book;


drop table person;
delete
from book
where true;

delete
from person
where true;

INSERT INTO book(name, author, year)
values ('a', 'as', 0);

SELECT *
FROM book
         join person p on p.id = Book.person_id
where p.id IS NULL;