create table person
(
    id   int primary key generated by default as identity,
    name varchar(100) not null,
    age  int
);

create table passport
(
    person_id int primary key references person (id) on delete cascade,
    number    int not null
);

drop table passport;

drop table person;

select *
from person;

select *
from passport;



create table person
(
    id   int primary key generated by default as identity,
    name varchar(100) not null,
    age  int
);


create table passport
(
    id   int primary key generated by default as identity,
    person_id int unique references person (id) on delete cascade,
    number    int not null
);