CREATE TABLE Person
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    year int
);


CREATE TABLE Book
(
    id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int         REFERENCES person (id) ON DELETE SET NULL,
    name      varchar(50) NOT NULL,
    author    varchar(50) NOT NULL,
    year      int
);

INSERT INTO person(name, year) VALUES ('Ivanon Ivan Ivanovich', 1970);
INSERT INTO person(name, year) VALUES ('Petrov Petro Petrovich', 1980);
INSERT INTO person(name, year) VALUES ('Oleksiev Oleksii Oleksiovich', 1990);

INSERT INTO book(person_id, name, author, year) VALUES (1, 'The Catcher in the Rye', 'J. D. Salinger', 1951);
INSERT INTO book(person_id, name, author, year) VALUES (1, 'Being and Time', 'Martin Heidegger', 1927);
INSERT INTO book(person_id, name, author, year) VALUES (null, 'Thinking in Java', 'Bruce Eckel', 1998);
INSERT INTO book(person_id, name, author, year) VALUES (2, 'Thief of Time', 'Terry Pratchett', 2001);

select * from book;

select * from person;

drop table book;


drop table person;
delete from book where true;

delete from person where true;

INSERT INTO book(name, author, year) values('a', 'as', 0);

SELECT * FROM book join person p on p.id = Book.person_id where p.id IS NULL;