create table actor
(
    id   int primary key generated by default as identity,
    name varchar(100) not null,
    age  int
);

create table movie
(
    id   int primary key generated by default as identity,
    name varchar(200) not null,
    year  int
);

create table actor_movie
(
    actor_id int references actor(id),
    movie_id int references movie(id),
    primary key(actor_id, movie_id)
);

select * from actor;

select * from movie;

select * from actor_movie;
